config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "commutes#index"

resources :reviews

  resources :commutes do
    resources :reviews
  end

  namespace :api do
    namespace :v1 do
      resources :commutes
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commute.rb
class Commute < ApplicationRecord
  belongs_to :user
  has_many :reviews, :dependent => :destroy

  validates :starting_location, presence: true
  validates :ending_location, presence: true
  validates :time, inclusion: { in: ["Early Morning", "Morning", "Afternoon", "Early Evening", "Evening", "Night"] }
  validates :mode, inclusion: { in: ["Train", "Walk", "Automobile", "Bike"] }

  METHODS = [
    ["Train", "Train"],
    ["Walk", "Walk"],
    ["Automobile", "Automobile"],
    ["Bike", "Bike"]
  ]

  TIMES = [
    ["Early Morning", "Early Morning"],
    ["Morning", "Morning"],
    ["Afternoon", "Afternoon"],
    ["Early Evening", "Early Evening"],
    ["Evening", "Evening"],
    ["Night", "Night"]
  ]

  def self.search(query)
    query = "%#{query}%"
    where("(starting_location like ? or ending_location like ?)", query, query)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :commute
  has_many :votes

  STARS = [
    ["*", 1],
    ["* *", 2],
    ["* * *", 3],
    ["* * * *", 4],
    ["* * * * *", 5]
  ]

  validates :comment, presence: true
  validates :review_stars, presence: true, numericality: true
  validates :user_id, presence: true, numericality: true
  validates :commute_id, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo_url, PhotoUrl

  has_many :commutes
  has_many :reviews
  has_many :votes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :admin, inclusion: { in: [ true, false ] }
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :upvote, inclusion: { in: [ true, false ] }
end

app/controllers/api/v1/commutes_controller.rb
class Api::V1::CommutesController < ApplicationController
  def index
    render json: Commute.all
  end

  def show
    render json: Commute.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 protect_from_forgery with: :exception

 before_action :configure_permitted_parameters, if: :devise_controller?



 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :photo_url])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :email, :photo_url])
 end
end

app/controllers/commutes_controller.rb
class CommutesController < ApplicationController

  def create
    @mode_collection = Commute::METHODS
    @times = Commute::TIMES
    @commute = Commute.new(commute_params)
    if @commute.save
      flash[:alert] = "Commute added successfully"
      redirect_to commute_path(@commute)
    else
      flash[:errors] = @commute.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @commute = Commute.find(params[:id])
    @reviews = @commute.reviews
  end

  def new
    @mode_collection = Commute::METHODS
    @times = Commute::TIMES
    @commute = Commute.new
  end

  def edit
    @mode_collection = Commute::METHODS
    @times = Commute::TIMES
    @commute = Commute.find(params[:id])
  end

  def update
    @mode_collection = Commute::METHODS
    @times = Commute::TIMES
    @commute = Commute.find(params[:id])
    if @commute.update(commute_params)
      redirect_to @commute, notice: 'Commute was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @commute = Commute.find(params[:id])
    @commute.destroy
    redirect_to root_path, notice: 'Commute was successfully destroyed.'
  end

  def index
    if params[:search]
      @commutes = Commute.search(params[:search]).order("created_at DESC")
    else
      @commutes = Commute.all.order('created_at DESC')
    end
  end

  private

  def commute_params
    params.require(:commute).permit(:starting_location, :ending_location, :mode, :time, :description, :user_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @stars = Review::STARS
    @review = Review.new
    @commute = Commute.find(params[:commute_id])
  end

  def create
    @stars = Review::STARS
    if current_user
      @review = Review.new(review_params)
      @commute = Commute.find(params[:commute_id])

      @review.user = current_user

      if @review.save
        ReviewMailer.receipt.deliver_now

        redirect_to @commute,
        notice: "Review added successfully!"
      else
        render :new, notice: "There's been a problem!"
      end
    else
      redirect_to root_path,
      alert: "You cannot add reviews until you are signed in"
    end
  end

  def edit
    @stars = Review::STARS
    @review = Review.find(params[:id])
    @commute = @review.commute
  end

  def update
    @stars = Review::STARS
    @review = Review.find(params[:id])
    @commute = @review.commute
    if @review.update(review_params)
      redirect_to @commute, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @commute = @review.commute
    @review.destroy
    redirect_to @commute, notice: 'Your review was successfully destroyed.'
  end

  private

  def review_params
    params.require(:review).permit(:comment, :review_stars).merge(commute: Commute.find(params[:commute_id]))
  end
end

app/views/commutes/edit.html.erb
<h1>Edit Commute</h1>

<%= form_for(@commute) do |f| %>
  <% if @commute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commute.errors.count, "error") %> prohibited this commute from being saved:</h2>

      <ul>
      <% @commute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :starting_location, "Starting Location" %><br/>
  <%= f.text_field :starting_location %>
  <br /><br />
  <%= f.label :ending_location, "Ending Location" %><br/>
  <%= f.text_field :ending_location %>
  <br /><br />
  <%= f.label :mode, "Mode of Transportation" %><br/>
  <%= f.collection_radio_buttons(:mode, @mode_collection, :first, :last)%>
  <br /><br />
  <%= f.label :time, "Time of day"%><br/>
  <%= f.select :time, @times %>
  <br /><br />
  <%= f.label :description %><br/>
  <%= f.text_area :description %>
  <br /><br/>
  <%= f.submit "Edit Commute" %>
<% end %>

app/views/commutes/index.html.erb
<h1>All Aboard! </h1>

<div class="search-form">
  <%= form_tag(commutes_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Commutes" %>
  <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>

<div id="app"></div>

<div class="search-results">
  <% if params[:search].present? %>
    <% if @commutes.present? %>
      <p>Search Results for: "<%= params[:search] %>":</p>

      <% @commutes.each do |commute| %>
        <%= link_to "#{commute.starting_location}-#{commute.ending_location}", commute_path(commute) %>
        <br/>
      <% end %>
    <% else %>
       <p>There are no commutes with the term <%= params[:search] %>.</p>
    <% end %>
  <% end %>
</div>

<%= link_to "Post Commute", new_commute_path %>

app/views/commutes/new.html.erb
<h1>New Commute Form</h1>

<%= form_for(@commute) do |f| %>
  <% if @commute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commute.errors.count, "error") %> prohibited this commute from being saved:</h2>

      <ul>
      <% @commute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :starting_location, "Starting Location" %><br/>
  <%= f.text_field :starting_location %>
  <br /><br />
  <%= f.label :ending_location, "Ending Location" %><br/>
  <%= f.text_field :ending_location %>
  <br /><br />
  <%= f.label :mode, "Mode of Transportation" %><br/>
  <%= f.collection_radio_buttons(:mode, @mode_collection, :first, :last)%>
  <br /><br />
  <%= f.label :time, "Time of day"%><br/>
  <%= f.select :time, @times, selected: "Morning" %>
  <br /><br />
  <%= f.label :description %><br/>
  <%= f.text_area :description %>
  <br /><br />
  <%= f.hidden_field :user_id, :value=>current_user.id %>
  <br /><br/>
  <%= f.submit "Add Commute" %>
<% end %>

app/views/commutes/show.html.erb
<h1><%= @commute.starting_location %> -to- <%= @commute.ending_location %></h1>

<div id="app"></div>

<div class="commute-links">
  <% if user_signed_in? && (@commute.user == current_user || current_user.admin == true)%>
    <%= link_to 'Delete Commute', @commute, method: :delete, data: { confirm: 'Are you sure you want to delete this commute?' } %>
    <%= link_to 'Edit Commute', edit_commute_path(@commute) %>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to "Add a Review", new_commute_review_path(@commute) %>
<% end %>

<% @reviews.each do |r| %>
  <p>
    <strong>Reviewer:</strong> <%= r.user.username %> </br>
    <strong>Stars:</strong> <%= r.review_stars %> stars awarded </br>
    <strong>Comment:</strong> <%= r.comment %> </br>
    <strong>Created at:</strong> <%= r.created_at.strftime("%B %d %Y")  %>

    <% if user_signed_in? && (r.user.username == current_user.username || current_user.admin == true)%>
      <br />
      <%= link_to 'Delete Review', r, method: :delete, data: { confirm: 'Are you sure you want to delete this commute?' } %>
      ||
      <%= link_to 'Edit Review', edit_review_path(r) %>
    <% end %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="transbox">
    <div class="nav-bar">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= link_to "Home Page", root_path %>
      <br />
      <% if user_signed_in? %>
        <% if current_user.photo_url.file != nil %>
          <img class="photo" src="<%= current_user.photo_url %>">
        <% end %>
        Hello, <%= current_user.username %>!
        <%= link_to "Edit Account", edit_user_registration_path %>
          ||
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path %>
          ||
        <%= link_to 'Sign In', new_user_session_path %>
      <% end %>
    </div>

      <%= yield %>
  </div>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Editing your review for  <%=@commute.starting_location%> - <%=@commute.ending_location%></h1>

<%= form_for([@commute, @review])  do |f| %>

  <% if @review.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@review.errors.count, 'error') %> prohibited this review from being saved:
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |m| %>
          <li>
            <%= m %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :review_stars %>
    <%= f.select :review_stars, @stars %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>

  <div class="actions">
    <%= f.submit 'Edit Review' %>
  </div>


<% end %>

app/views/reviews/new.html.erb
<h1>Review Form for <%=@commute.starting_location%> - <%=@commute.ending_location%></h1>

<%= form_for([@commute, @review])  do |f| %>

  <% if @review.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@review.errors.count, 'error') %> prohibited this review from being saved:
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |m| %>
          <li>
            <%= m %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :review_stars %>
    <%= f.select :review_stars, @stars, selected: 3 %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>

  <div class="actions">
    <%= f.submit 'Add Review' %>
  </div>


<% end %>

app/views/static_pages/index.html.erb
<h1>All Aboard! </h1>
<div id="app">
</div>